### ISSUE TITLE
packaging

### ISSUE THREAD

**Issue by mostafaasadi** [TheAMM/mpv_thumbnail_script#10]
Hi 
I was searching this [featur](https://github.com/mpv-player/mpv/issues/3940) for mpv since 2016 😄 
till today someone post your script github on that issue.
thank you for your amazing helpful script. 🌹 
I can package it for debian/ubuntu/arch/windows if you want easy install

**Comment by TheAMM** [comment]
I'm curious about what exactly you mean by packaging it, but no.
The "install" involves copying two files into a directory (in the future, one), and if you mean package manager packages, no. If I wanted those I'd make them myself, but I don't; this script has (still) reasonably active development, and mpv packages are generally horribly outdated; the osc.lua this script patches requires at least 0.27.
Thanks for the interest though, and glad it's of use.
