### ISSUE TITLE
Can't click seekbar nor any on-screen buttons on Lubuntu

### ISSUE THREAD

**Issue by iiiGerardoiii** [TheAMM/mpv_thumbnail_script#13]
The thumbnails show up when I hover the cursor on the seekbar, but I can't click on it. If I doubleclick on the seekbar, the video goes fullscreen as if there was no UI.

I've tried this on my other laptop that also has Lubuntu and it doesn't work there either.

I'm using:
mpv_thumbnail_script v0.4.1
mpv 0.26.0
Lubuntu 17.10.1

**Comment by TheAMM** [comment]
Readme says:
> **Note:** You will need a rather new version of mpv due to [the new binds](https://github.com/mpv-player/mpv/commit/957e9a37db6611fe0879bd2097131df5e09afd47#diff-5d10e79e2d65d30d34f98349f4ed08e4) used in the patched `osc.lua`.

Update your mpv and report back. Lubuntu has nothing to do with this.

**Comment by iiiGerardoiii** [comment]
Oh I thought that was the latest version, my bad.

I just updated and the problem is gone, thanks!
