### ISSUE TITLE
no more Shift+T for Floating (osx)

### ISSUE THREAD

**Issue by mrkapqa** [TheAMM/mpv_thumbnail_script#22]
Hello ,

i installed your lua script for generating thumbnails,
and it works beautifully, thank you very much.

However, upon installing, afterwards i noticed some strange behaviour,
for example i can no longer let the window "float" on top.

when i press Shift-T now it says "Started Thumbnailer Jobs" instead of the desired "stay on top"

**Comment by TheAMM** [comment]
Disable the default keybind and optionally add your own.

[Readme](https://github.com/TheAMM/mpv_thumbnail_script#configuration) says:
> With `disable_keybind=yes`, you can add your own keybind to [`input.conf`](https://mpv.io/manual/master/#input-conf) with `script-binding generate-thumbnails`, for example:
> ```ini
> shift+alt+s script-binding generate-thumbnails
> ```
