### ISSUE TITLE
Feature request: recognize on-screen-controls set to layout=topbar and change borders

### ISSUE THREAD

**Issue by UserNaem** [TheAMM/mpv_thumbnail_script#24]
The script draws borders on left, right, and top edges of the thumnail frame, assuming the on-screen controls are set to "bottom bar" (default), but if you use topbar, it looks like this:
![image](https://user-images.githubusercontent.com/21028464/46939469-cdfaf480-d07f-11e8-91b7-7cd7a5bad55e.png)

**Comment by TheAMM** [comment]
https://github.com/TheAMM/mpv_thumbnail_script/blob/master/src/options.lua#L55-L63
