### ISSUE TITLE
Is it possible to store the image with lesser space

### ISSUE THREAD

**Issue by laichiaheng** [TheAMM/mpv_thumbnail_script#27]
It still takes too much space to store the image on my 2TB HDD.

**Comment by TheAMM** [comment]
You can make the resolution smaller or render fewer thumbnails, but the images have to be in raw RGBA format and on disk for mpv to load them. Technically they could be saved as JPEGs or PNGs, but would then require converting each one when they're needed, which is a hassle and a waste of cycles.
