### ISSUE TITLE
Thumbnail cache directory

### ISSUE THREAD

**Issue by bluefiberbread** [TheAMM/mpv_thumbnail_script#29]
How do I change the cache directory to "F:\Cache\mpv"

**Comment by Hrxn** [comment]
https://github.com/TheAMM/mpv_thumbnail_script#configuration

`cache_directory=F:\Cache\mpv`

**Comment by bluefiberbread** [comment]
I thought that'd work too but it didn't

**Comment by Hrxn** [comment]
Works for me (tm + r)..

Config paths etc. correct?
https://mpv.io/manual/master/#files

**Comment by bluefiberbread** [comment]
Yeah, it's in `C:\Program Files\mpv\scripts` and the script itself works, but when I change the cache directory to the below, it won't work  
```
local thumbnailer_options = {
    -- The thumbnail directory
    `cache_directory=F:\Cache\mpv,
```

**Comment by TheAMM** [comment]
@bluefiberbread Do not edit the .lua, edit the .conf. [Read the readme thoroughly](https://github.com/TheAMM/mpv_thumbnail_script#configuration).
(Although, instead of `lua-settings`, you should name the directory `script-opts`.)
