### ISSUE TITLE
Unstable behaviour while catching thumbs (with mpv)

### ISSUE THREAD

**Issue by waxfingers** [TheAMM/mpv_thumbnail_script#3]
Till the thumbnails' caching is done, a "ghost instance" of mpv jumps like crazy in the dock; till all thumbs are generated it is impossible to access mpv in fullscreen mode as it just keeps changing space (screen). This behaviour happens both in shorter than 3600" videos and in longer ones - script trigered by keybind. NOT the case if using ffmpeg as per lua seting conf.

mpv 0.27.0
OSX 10.11.6
mpv_thumbnail_script 0.3.0

Have to say, great plug!! Congrats and thank you =)

**Comment by TheAMM** [comment]
Hmm. This is because mpv is being called in the background.
I don't have a Mac to test on (and don't know much about the ecosystem), so this could get complicated.

So let's try the first thing I can come up with.
Olease edit the `mpv_thumbnail_script_server.lua` near line 417, adjust it as follows:
```diff
diff --git a/mpv_thumbnail_script_server.lua b/new.lua
index 6a9686e..94e00ab 100644
--- a/mpv_thumbnail_script_server.lua
+++ b/new.lua
@@ -417,6 +417,7 @@ function create_thumbnail_mpv(file_path, timestamp, size, output_path)
         "mpv",
         -- Hide console output
         "--msg-level=all=no",
+        "--player-operation-mode=cplayer",
         file_path,
 
         -- Disable ytdl
```
(Add the `"--player-operation-mode=cplayer",` without the leading `+`)

This might fix it, so fingers crossed.

**Comment by waxfingers** [comment]
I'm afraid it did not... but got it a bit narrowed down; it only occurs when opening the files by double clicking them in the finder, from the terminal behaviour is ok. OT but just thought it could be useful to have a settings to choose IF automatically delete thumbs from temp once video is closed.

**Comment by Akemi** [comment]
this should be fixed with the next mpv release. the [fix](https://github.com/mpv-player/mpv/commit/77021cf6fe6a1813b832c8927c288e958b6f6845) is currently only in mpv master.

**Comment by TheAMM** [comment]
Closing this in advance unless something new pops up.
