### ISSUE TITLE
Unexpected behavior of windows services and antimalware

### ISSUE THREAD

**Issue by sethazazel** [TheAMM/mpv_thumbnail_script#31]
I had a issue today
[https://github.com/mpv-player/mpv/issues/6392](https://github.com/mpv-player/mpv/issues/6392)
I solved it by delete mpv_thumbnail_script_client_osc.lua and mpv_thumbnail_script_server.lua
i don't know what causes it but i thought i should inform you.

**Comment by TheAMM** [comment]
There should be nothing unexpected about this. The script starts up to 150 subprocesses (by default) which each thumbnail a frame. That takes processing power, and your antivirus can freak about it.
Disable the thumbnail autogeneration in the options or readjust performance expectations.

**Comment by sethazazel** [comment]
the problem is not only anti malware, another windows service too. its normal to use cpu mpv always use %20-30 and i am ok with that because i know why it use. But this windows service not stopping after all thumbnails created it's end when you close the video. I don't think it's normal.

**Comment by TheAMM** [comment]
The script does not do anything service-related, and I can't replicate the issue.

**Comment by sethazazel** [comment]
it's odd i check last updates and find that windows was updated same day. Before that there was't any issue . i think it's somehow related. Thank you for replies.
