### ISSUE TITLE
Thumbnailing works for local videos but not remote videos (Youtube, Vimeo)

### ISSUE THREAD

**Issue by pwindle** [TheAMM/mpv_thumbnail_script#36]
On Windows 10. Thumbnailing works for local videos but fails for remote videos - with no obvious warnings or errors. I've only tried Youtube and Vimeo. Any help would be appreciated. Thanks in advance.

Log file:
[mpv-log.txt](https://github.com/TheAMM/mpv_thumbnail_script/files/3124004/mpv-log.txt)

mpv.conf
```
no-border
#cache=1048576
cursor-autohide=200
keep-open
autofit-larger=100%x95%
#cursor-autohide-fs-only
pause=no
no-pause
# For thumbnails lua script:
osc=no



[extension.jpg]
#osd-level=0
#osd-bar=no
pause=yes

[extension.png]
#osd-level=0
#osd-bar=no
pause=yes

[extension.gif]
loop-file=yes
no-pause

[extension.webm]
loop-file=yes
no-pause

[extension.mp4]
loop-file=yes
no-pause
```

console output:
```
~
> mpv https://www.youtube.com/watch?v=MkE2lxkw00w
Playing: https://www.youtube.com/watch?v=MkE2lxkw00w
 (+) Video --vid=1 (*) (vp9 320x240 29.970fps)
 (+) Audio --aid=1 --alang=eng (*) 'DASH audio' (vorbis 2ch 44100Hz) (external)
AO: [wasapi] 44100Hz stereo 2ch float
VO: [gpu] 320x240 yuv420p
(Paused) AV: 00:00:00 / 00:03:14 (0%) A-V:  0.000 Cache: 193s+5MB
```

mpv --version:
```
~
> mpv --version
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.19.101
   libavcodec      58.30.100
   libavformat     58.18.100
   libswscale      5.2.100
   libavfilter     7.31.100
   libswresample   3.2.100
ffmpeg version: 4.1+1209.ge320f9576a
```

Screenshot:
![mpv-thumbnailing2](https://user-images.githubusercontent.com/28284434/56851062-97d9df80-6902-11e9-9cdc-6a26f45f67c5.jpg)

**Comment by TheAMM** [comment]
[`thumbnail_network` defaults to `no`](https://github.com/TheAMM/mpv_thumbnail_script/blob/master/src/options.lua#L109-L110).
Add `thumbnail_network=yes` in [the configuration file](https://github.com/TheAMM/mpv_thumbnail_script#configuration).

**Comment by pwindle** [comment]
Ah I see I should have read the front page more thoroughly. Thanks that works perfectly.
