### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by pavelxdd** [TheAMM/mpv_thumbnail_script#4]
Hello. 

1) Can you add a script option to enable `--no-config` argument? The script stucks on generating thumbnails unless I add this argument to `server.lua`.

2) Could be useful to have an option to specify `--profile` argument with specific profile name for generating thumbnails.

**Comment by TheAMM** [comment]
Sure, but can you elaborate on the stuck generation?
Platform, config file?

**Comment by pavelxdd** [comment]
Windows 10, x64
config: http://sprunge.us/XIZM

> can you elaborate on the stuck generation?

Strange thing, I can't reproduce it today. I swear yesterday without adding `no-config` it just didn't generate thumbnails at all, the counter above the thumbnail placeholder stayed at zero, or very close to zero (10/380 for example), and didn't increase. There were no errors in console other than messages that the thumbnail size isn't the same as before and should be regenerated.

**Comment by TheAMM** [comment]
Well, I added some extra logging behind a new option, so if it happens again you can get logs out of each sub-mpv call.
The script overall is fairly robust, but it lacks proper error logging (it doesn't really try to figure out what went wrong, just that something went wrong and we should bail).
