### ISSUE TITLE
Thumbnailing command failed

### ISSUE THREAD

**Issue by weearc** [TheAMM/mpv_thumbnail_script#50]
### OS
Arch Linux with linux kernel 5.2
### mpv version
0.32.0_5_g2fd34889fe
### error log
[000000.bgra.log](https://github.com/TheAMM/mpv_thumbnail_script/files/4133561/000000.bgra.log)
### console log
```bash
[mpv_thumbnail_script_client_osc] The 'tick' event is deprecated and will be removed.
AV: 00:00:00 / 00:23:40 (0%) A-V:  0.000
[mpv_thumbnail_script_server] Thumbnailing command failed! 
[mpv_thumbnail_script_server] mpv process error: nil 
[mpv_thumbnail_script_server] Process stdout:  
[mpv_thumbnail_script_server] Debug log: /tmp/mpv_thumbs_cache/YGNeo.subEndro01GB1080PMP4-481353632/000000.bgra.log 
[mpv_thumbnail_script_server] Output file missing! /tmp/mpv_thumbs_cache/YGNeo.subEndro01GB1080PMP4-481353632/000000.bgra
```

**Comment by ghost** [comment]
the same thing happens to me to, arch with linux 5.2

**Comment by blankname** [comment]
Make sure you're using the latest version.
The following merged pull request looks relevant:
https://github.com/TheAMM/mpv_thumbnail_script/pull/49

**Comment by nunu-bit** [comment]
Same error on Win 10.

**Comment by weearc** [comment]
#49 Fixed. Thanks a lot.
