### ISSUE TITLE
Thumbnailing stopped working after mpv update (v2:0.32.0+git~bionic1)

### ISSUE THREAD

**Issue by fnadde42** [TheAMM/mpv_thumbnail_script#51]
I suspect that the `2:0.32.0+git~bionic1` release of mpv broke something in the image thumbnailer. Getting this error message 

```
[mpv_thumbnail_script_server] Thumbnailing command failed! 
[mpv_thumbnail_script_server] mpv process error: nil 
[mpv_thumbnail_script_server] Process stdout:  
[mpv_thumbnail_script_server] Debug log: /tmp/my_mpv_thumbnails/myexamplemovie-1775712629/000032.bgra.log 
[mpv_thumbnail_script_server] Output file missing! /tmp/my_mpv_thumbnails/myexamplemovie-1775712629/000032.bgra 
```

### Debug-info

```
$ mpv --version
mpv git-2020-02-01-f304a79 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Fri Feb 21 02:24:22 UTC 2020
ffmpeg library versions:
   libavutil       56.38.100
   libavcodec      58.67.100
   libavformat     58.37.100
   libswscale      5.6.100
   libavfilter     7.72.100
   libswresample   3.6.100
ffmpeg version: git-2020-02-01-843c24a
```

mpv_thumbnail_script_client_osc.lua:
```
    mpv_thumbnail_script.lua 0.4.2 - commit a2de250 (branch master)
    https://github.com/TheAMM/mpv_thumbnail_script
    Built on 2018-02-07 20:36:55
```

mpv_thumbnail_script_server.lua:
```
    mpv_thumbnail_script.lua 0.4.2 - commit a2de250 (branch master)
    https://github.com/TheAMM/mpv_thumbnail_script
    Built on 2018-02-07 20:36:54
```

- [mpv_console_output.txt](https://github.com/TheAMM/mpv_thumbnail_script/files/4241422/mpv_console_output.txt)
- [000000.bgra.log](https://github.com/TheAMM/mpv_thumbnail_script/files/4241426/000000.bgra.log)

**Comment by blankname** [comment]
See: https://github.com/TheAMM/mpv_thumbnail_script/issues/50#issuecomment-580940120

Please update to master before reporting issues as they may have already been fixed.

**Comment by fnadde42** [comment]
Ah! I just used the latest version. Maybe a new release should be published? `0.4.3`?

**Comment by hrxn** [comment]
I think grabbing the whole repo and then running `concat_files.py cat_osc.json` and `concat_files.py cat_server.json` should work as well, if I'm reading that right..

**Comment by fnadde42** [comment]
Of course, but people new to thumbnail script will not read this and go to the release page to get their copy and if they use a relatively new version of mpv, it will backfire.

**Comment by Quantum00** [comment]
I second releasing a new version. The dev has not been active since Dec22, maybe someone should put out a fork release? I'm currently using a build with @blankname's commit https://github.com/TheAMM/mpv_thumbnail_script/pull/55/commits/967a572bdddd6a8a555c159693b6ffd1225f16c3 merged.

**Comment by fnadde42** [comment]
@Quantum00 Let's first try to get a hold of @TheAMM before we start forking like crazy. I can try to contact the person.
