### ISSUE TITLE
I have an idea

### ISSUE THREAD

**Issue by hooke007** [TheAMM/mpv_thumbnail_script#59]
Hello.
Now I find that the script can just generate all the preview thumbnail, which will lead to much high CPU usage for a long time. For I usually enjoy the movies while my computer's performance is poor, so I have to pause to wait for the completion of the generating the thumbnails.

So I have a plan, how could it generate the thumb when and where I want ......

**Comment by ghost** [comment]
> 
> 
> Hello.
> Now I find that the script can just generate all the preview thumbnail, which will lead to much high CPU usage for a long time. For I usually enjoy the movies while my computer's performance is poor, so I have to pause to wait for the completion of the generating the thumbnails.
> 
> So I have a plan, how could it generate the thumb when and where I want ......

This is already possible. 
**"When":** Set `autogenerate_max_duration=3600` to `autogenerate_max_duration=1` in your `mpv_thumbnail_script.conf`, this will stop the thumbnailing process to start automatically in 99,9% of any video. As default, if you want to start the thumbnailing process just use the shortcut **Shift+T**.

**"Where":** In this exact same file, `mpv_thumbnail_script.conf`, you'll find something as `cache_directory=/tmp/my_mpv_thumbnails`, just replace with the location you want. Mine for example is `cache_directory=C:\Program Files (x86)\MPV Player\mpv\mpv_thumbs_cache`.

**Comment by hooke007** [comment]
> This is already possible.
> **"When":** Set `autogenerate_max_duration=3600` to `autogenerate_max_duration=0` in your `mpv_thumbnail_script.conf`, this will stop the thumbnailing process to start automatically. As default, if you want to start the thumbnailing process just use the shortcut **Shift+T**.
> 
> **"Where":** In this exact same file, `mpv_thumbnail_script.conf`, you'll find something as `cache_directory=/tmp/my_mpv_thumbnails`, just replace with the location you want. Mine for example is `cache_directory=C:\Program Files (x86)\MPV Player\mpv\mpv_thumbs_cache`.

No, I mean...Just generate the accurate frame I want (just like potplayer or other media player) rather than generate all the thumbnails at one time.

**Comment by sdsaati** [comment]
Hmm, true, it's a good idea, generating the thumbnails on the fly while seeking the video, if it is possible, it would be really nice!
