### ISSUE TITLE
Improve thumbnail "feel"

### ISSUE THREAD

**Issue by TheAMM** [TheAMM/mpv_thumbnail_script#7]
Currently thumbnails will be chosen by taking a timestamp and turning that into a thumbnail index by `math.floor`ing it with the thumbnail interval/delta.
This means the thumbnail being displayed is *before* the position the user would click on, and slightly misleading; the jump will rarely happen on the actual thumbnail timestamp (and overriding the seek would be a pain/detrimental for accurate seeking) but instead after the moment has passed.

This feels "wrong".
How do other players do it? Do they choose their thumbnail timestamps with some clever logic?
What logic do they use to choose which thumbnail to show? Is it a "closest" timestamp, the next thumbnail, or what?
The downside with displaying simply the next thumbnail would be short videos having their thumbnails be almost useless. Maybe move generate timestamps up by half an interval and choose the closest thumbnail?

----

This is here to allow others to chime in. What are your thoughts?

**Comment by pavelxdd** [comment]
Maybe that's because mpv defaults to `absolute-percent+keyframes` on seekbar click?
Is this PR mpv-player/mpv#5019 going to solve the issue, what do you think? You could change the default setting of the `client.lua` to something like `exact` or `absolute-percent` (without `keyframes`) - needs testing to find the best result.

**Comment by TheAMM** [comment]
Hmh, no, it seems that [*drags* are keyframed](https://github.com/TheAMM/mpv_thumbnail_script/blob/master/src/patched_osc.lua#L1949), [clicks are exact](https://github.com/TheAMM/mpv_thumbnail_script/blob/master/src/patched_osc.lua#L1963).
I'm fine with drags not being exact; if user is dragging, they're already ignoring the hovering thumbnails.

**Comment by pavelxdd** [comment]
What if you just add `--hr-seek=no` to mpv arguments?

**Comment by TheAMM** [comment]
The real solution is likely to go and try the half-advance I spoke about in the OP (so that if you move mouse from the left, the instant the thumbnail changes means seeking to that position *should* bring you at most `thumbnail_delta/2` seconds away from the thumbnailed scene - the scene should then pass by and not already be a past event), but circumstances stop me for the moment, so let's enjoy the holidays for now.
