### ISSUE TITLE
OSC panel disappears when moving to next video

### ISSUE THREAD

**Issue by Niotferdi** [TheAMM/mpv_thumbnail_script#74]
This happens when I go to the next file using the button on the OSC or the "playlist-next" command, or when I load the next file with the command "loadfile ...". The OSC panel disappears until the next start of the player.
I realized that this problem is caused by the "thumbnail_network = yes" parameter in mpv_thumbnail_script.conf. This parameter is critically important to me.
But the problem isn't just about video from the internet.
I made a copy of the directory with mpv, left in mpv.conf only the "osc = no" needed for the script to work - it did not help.

**Comment by Czarnodziej** [comment]
Seems to be fixed in https://github.com/TheAMM/mpv_thumbnail_script/pull/55

**Comment by Niotferdi** [comment]
Thanks for supporting your project.

I solved the problem described in this post by making changes to the script that I found elsewhere.
Just in case, I'll leave a working solution here: https://pastebin.com/5LYjJy6Y
