### ISSUE TITLE
Thumbnail generation stuck at 0%

### ISSUE THREAD

**Issue by ghost** [TheAMM/mpv_thumbnail_script#95]
Thumbnails are always blank, and say "0%". Does anybody know of a way to fix this?

![mpv_PEkVkAZyAc](https://user-images.githubusercontent.com/75036751/181148534-ffb7b475-3a33-4d15-8db2-8602eb6c6918.png)

**Comment by norpol** [comment]
This should fix it https://github.com/TheAMM/mpv_thumbnail_script/issues/91

**Comment by ghost** [comment]
> This should fix it #91

I've tried this. It didn't work for me :/

**Comment by norpol** [comment]
Does mpv say anything on the command-line when you're starting to play a video?

For me the error message before chaning the `--o` to `-o` was:

```
[mpv_thumbnail_script_server] Thumbnailing command failed!
[mpv_thumbnail_script_server] mpv process error: nil
[mpv_thumbnail_script_server] Process stdout:
[mpv_thumbnail_script_server] Debug log: /tmp/mpv_thumbs_cache/S01E02-842550121/000000.bgra.log
[mpv_thumbnail_script_server] Output file missing! /tmp/mpv_thumbs_cache/S01E02-842550121/000000.bgra
```

**Comment by ghost** [comment]
I'm not sure what command-line you mean, but mpv itself isn't giving me any errors when I start playing a video.
Where do I check the error log?

**Comment by hrxn** [comment]
Guys....
Just use the fork: https://github.com/marzzzello/mpv_thumbnail_script

**Comment by ghost** [comment]
Alright, thank you, but now that I'm using the fork it tells me "Thumbnailing failed, check console for more details".
I don't know how to check the console. The mpv manual says that the console is displayed on the video window, but it isn't.

**Comment by hrxn** [comment]
No console is displayed by default.. there is a built-in console though, it's bound to the backtick key by default, but you can obviously rebind it..

https://github.com/mpv-player/mpv/blob/master/etc/input.conf#L95

```
#` script-binding console/enable        # open the console
```

**Comment by ghost** [comment]
Console output

![PtgxOGqpKW](https://user-images.githubusercontent.com/75036751/183256611-b543d28f-c04e-41c7-a29c-9ecf6c7f973f.png)

**Comment by ghost** [comment]
My dumbass didn't set the right cache directory for the thumbnails in my `mpv_thumbnail_script.conf`. 
It's fixed now, thanks for the help!
