### ISSUE TITLE
not wokring :( 

### ISSUE THREAD

**Issue by OmiChrome** [TheAMM/mpv_thumbnail_script#99]
![image](https://user-images.githubusercontent.com/108952834/189445744-29ce0fe0-0ff4-4afb-b4f1-5b2e440534c6.png)
#91  is not also working for me

**Comment by shishtpal** [comment]
Not working for me!
```log
[   0.004][v][cplayer] mpv 0.34.0-468-gba81e4ed88 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
[   0.005][v][cplayer]  built on Sun Sep 18 12:28:04 2022
[   0.005][v][cplayer] FFmpeg library versions:
[   0.005][v][cplayer]    libavutil       57.36.102
[   0.005][v][cplayer]    libavcodec      59.44.100
[   0.005][v][cplayer]    libavformat     59.32.100
[   0.005][v][cplayer]    libswscale      6.8.112
[   0.005][v][cplayer]    libavfilter     8.49.100
[   0.005][v][cplayer]    libswresample   4.9.100
[   0.005][v][cplayer] FFmpeg version: git-2022-09-17-ed83a3a5b
[   0.005][v][cplayer] 
[   0.005][v][cplayer] Configuration: meson build -Dprefix=/__w/mpv-winbuild-cmake/mpv-winbuild-cmake/build64-v3/install/mingw
[   0.005][v][cplayer] List of enabled features: av-channel-layout build-date cplayer cuda-hwaccel cuda-interop d3d-hwaccel d3d11 d3d9-hwaccel direct3d dos-paths dvdnav egl-angle egl-angle-win32 egl-helpers ffmpeg ffnvcodec gl gl-dxinterop gl-dxinterop-d3d9 gl-win32 glob glob-win32 gpl iconv javascript jpeg jpegxl lcms2 libarchive libass libavdevice libbluray libm libmpv-shared libplacebo libplacebo-next luajit manpage-build noexecstack openal optimize pdf-build plain-gl rubberband rubberband-3 sdl2 sdl2-audio sdl2-gamepad sdl2-video shaderc spirv-cross stdatomic threads uchardet vapoursynth vector vulkan wasapi win32 win32-desktop win32-executable win32-internal-pthreads zimg zlib
[   0.005][v][cplayer] Built with NDEBUG.
[   0.005][v][cplayer] Command line options: '--msg-level=all=no' '--no-ytdl' '--user-agent=libmpv' '--referrer=' '--hwdec=no' '--log-file=C:\Windows\TEMP\mpv_thumbs_cache\Background Removal Like Zoom  OpenCV Python CVZone k7cVPGpnels-41478009\000000.bgra.log' 'Background Removal Like Zoom ｜ OpenCV Python CVZone [k7cVPGpnels].mp4' '--start=4.720617' '--frames=1' '--hr-seek=yes' '--no-audio' '--vf=scale=200:112' '--vf-add=format=bgra' '--of=rawvideo' '--ovc=rawvideo' '--o' 'C:\Windows\TEMP\mpv_thumbs_cache\Background Removal Like Zoom  OpenCV Python CVZone k7cVPGpnels-41478009\000000.bgra'
[   0.005][v][cplayer] mpv 0.34.0-468-gba81e4ed88 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
[   0.005][v][cplayer]  built on Sun Sep 18 12:28:04 2022
[   0.005][v][cplayer] FFmpeg library versions:
[   0.005][v][cplayer]    libavutil       57.36.102
[   0.005][v][cplayer]    libavcodec      59.44.100
[   0.005][v][cplayer]    libavformat     59.32.100
[   0.005][v][cplayer]    libswscale      6.8.112
[   0.005][v][cplayer]    libavfilter     8.49.100
[   0.005][v][cplayer]    libswresample   4.9.100
[   0.005][v][cplayer] FFmpeg version: git-2022-09-17-ed83a3a5b
[   0.005][v][cplayer] 
[   0.005][v][cplayer] Configuration: meson build -Dprefix=/__w/mpv-winbuild-cmake/mpv-winbuild-cmake/build64-v3/install/mingw
[   0.005][v][cplayer] List of enabled features: av-channel-layout build-date cplayer cuda-hwaccel cuda-interop d3d-hwaccel d3d11 d3d9-hwaccel direct3d dos-paths dvdnav egl-angle egl-angle-win32 egl-helpers ffmpeg ffnvcodec gl gl-dxinterop gl-dxinterop-d3d9 gl-win32 glob glob-win32 gpl iconv javascript jpeg jpegxl lcms2 libarchive libass libavdevice libbluray libm libmpv-shared libplacebo libplacebo-next luajit manpage-build noexecstack openal optimize pdf-build plain-gl rubberband rubberband-3 sdl2 sdl2-audio sdl2-gamepad sdl2-video shaderc spirv-cross stdatomic threads uchardet vapoursynth vector vulkan wasapi win32 win32-desktop win32-executable win32-internal-pthreads zimg zlib
[   0.005][v][cplayer] Built with NDEBUG.
[   0.005][d][global] config path: '' -> 'D:\Softwares\mpv\bin'
[   0.005][d][global] user path: '~~home/' -> 'D:\Softwares\mpv\bin'
[   0.005][d][global] user path: '~~old_home/' -> ''
[   0.005][d][global] config path: 'encoding-profiles.conf' -/-> 'D:\Softwares\mpv\bin/encoding-profiles.conf'
[   0.005][d][global] config path: 'mpv.conf' -> 'D:\Softwares\mpv\bin/mpv.conf'
[   0.005][d][global] config path: 'config' -/-> 'D:\Softwares\mpv\bin/config'
[   0.005][v][cplayer] Reading config file D:\Softwares\mpv\bin/mpv.conf
[   0.005][v][cplayer] Applying profile 'default'...
[   0.005][v][cplayer] Setting option 'profile' = 'gpu-hq' (flags = 4)
[   0.005][v][cplayer] Applying profile 'gpu-hq'...
[   0.005][v][cplayer] Setting option 'scale' = 'spline36' (flags = 4)
[   0.005][v][cplayer] Setting option 'cscale' = 'spline36' (flags = 4)
[   0.005][v][cplayer] Setting option 'dscale' = 'mitchell' (flags = 4)
[   0.005][v][cplayer] Setting option 'dither-depth' = 'auto' (flags = 4)
[   0.005][v][cplayer] Setting option 'correct-downscaling' = 'yes' (flags = 4)
[   0.005][v][cplayer] Setting option 'linear-downscaling' = 'yes' (flags = 4)
[   0.005][v][cplayer] Setting option 'sigmoid-upscaling' = 'yes' (flags = 4)
[   0.005][v][cplayer] Setting option 'deband' = 'yes' (flags = 4)
[   0.005][v][cplayer] Setting option 'deband' = 'no' (flags = 4)
[   0.005][v][cplayer] Setting option 'osc' = 'no' (flags = 4)
[   0.005][v][cplayer] Setting option 'msg-level' = 'all=no' (flags = 8)
[   0.005][v][cplayer] Setting option 'ytdl' = 'no' (flags = 8)
[   0.005][v][cplayer] Setting option 'user-agent' = 'libmpv' (flags = 8)
[   0.005][v][cplayer] Setting option 'referrer' = '' (flags = 8)
[   0.005][v][cplayer] Setting option 'hwdec' = 'no' (flags = 8)
[   0.005][v][cplayer] Setting option 'log-file' = 'C:\Windows\TEMP\mpv_thumbs_cache\Background Removal Like Zoom  OpenCV Python CVZone k7cVPGpnels-41478009\000000.bgra.log' (flags = 8)
[   0.005][v][cplayer] Setting option 'start' = '4.720617' (flags = 8)
[   0.005][v][cplayer] Setting option 'frames' = '1' (flags = 8)
[   0.005][v][cplayer] Setting option 'hr-seek' = 'yes' (flags = 8)
[   0.005][v][cplayer] Setting option 'audio' = 'no' (flags = 8)
[   0.005][v][cplayer] Setting option 'vf' = 'scale=200:112' (flags = 8)
[   0.005][v][cplayer] Setting option 'vf-add' = 'format=bgra' (flags = 8)
[   0.005][v][cplayer] Setting option 'of' = 'rawvideo' (flags = 8)
[   0.005][v][cplayer] Setting option 'ovc' = 'rawvideo' (flags = 8)
[   0.005][f][cplayer] Error parsing commandline option o: option requires parameter
[   0.005][w][cplayer] Make sure you're using e.g. '--o=value' instead of '--o value'.
[   0.005][i][cplayer] Exiting... (Fatal error)
```

**Comment by OmiChrome** [comment]
> Not working for me!
> 
> ```
> [   0.004][v][cplayer] mpv 0.34.0-468-gba81e4ed88 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
> [   0.005][v][cplayer]  built on Sun Sep 18 12:28:04 2022
> [   0.005][v][cplayer] FFmpeg library versions:
> [   0.005][v][cplayer]    libavutil       57.36.102
> [   0.005][v][cplayer]    libavcodec      59.44.100
> [   0.005][v][cplayer]    libavformat     59.32.100
> [   0.005][v][cplayer]    libswscale      6.8.112
> [   0.005][v][cplayer]    libavfilter     8.49.100
> [   0.005][v][cplayer]    libswresample   4.9.100
> [   0.005][v][cplayer] FFmpeg version: git-2022-09-17-ed83a3a5b
> [   0.005][v][cplayer] 
> [   0.005][v][cplayer] Configuration: meson build -Dprefix=/__w/mpv-winbuild-cmake/mpv-winbuild-cmake/build64-v3/install/mingw
> [   0.005][v][cplayer] List of enabled features: av-channel-layout build-date cplayer cuda-hwaccel cuda-interop d3d-hwaccel d3d11 d3d9-hwaccel direct3d dos-paths dvdnav egl-angle egl-angle-win32 egl-helpers ffmpeg ffnvcodec gl gl-dxinterop gl-dxinterop-d3d9 gl-win32 glob glob-win32 gpl iconv javascript jpeg jpegxl lcms2 libarchive libass libavdevice libbluray libm libmpv-shared libplacebo libplacebo-next luajit manpage-build noexecstack openal optimize pdf-build plain-gl rubberband rubberband-3 sdl2 sdl2-audio sdl2-gamepad sdl2-video shaderc spirv-cross stdatomic threads uchardet vapoursynth vector vulkan wasapi win32 win32-desktop win32-executable win32-internal-pthreads zimg zlib
> [   0.005][v][cplayer] Built with NDEBUG.
> [   0.005][v][cplayer] Command line options: '--msg-level=all=no' '--no-ytdl' '--user-agent=libmpv' '--referrer=' '--hwdec=no' '--log-file=C:\Windows\TEMP\mpv_thumbs_cache\Background Removal Like Zoom  OpenCV Python CVZone k7cVPGpnels-41478009\000000.bgra.log' 'Background Removal Like Zoom ｜ OpenCV Python CVZone [k7cVPGpnels].mp4' '--start=4.720617' '--frames=1' '--hr-seek=yes' '--no-audio' '--vf=scale=200:112' '--vf-add=format=bgra' '--of=rawvideo' '--ovc=rawvideo' '--o' 'C:\Windows\TEMP\mpv_thumbs_cache\Background Removal Like Zoom  OpenCV Python CVZone k7cVPGpnels-41478009\000000.bgra'
> [   0.005][v][cplayer] mpv 0.34.0-468-gba81e4ed88 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
> [   0.005][v][cplayer]  built on Sun Sep 18 12:28:04 2022
> [   0.005][v][cplayer] FFmpeg library versions:
> [   0.005][v][cplayer]    libavutil       57.36.102
> [   0.005][v][cplayer]    libavcodec      59.44.100
> [   0.005][v][cplayer]    libavformat     59.32.100
> [   0.005][v][cplayer]    libswscale      6.8.112
> [   0.005][v][cplayer]    libavfilter     8.49.100
> [   0.005][v][cplayer]    libswresample   4.9.100
> [   0.005][v][cplayer] FFmpeg version: git-2022-09-17-ed83a3a5b
> [   0.005][v][cplayer] 
> [   0.005][v][cplayer] Configuration: meson build -Dprefix=/__w/mpv-winbuild-cmake/mpv-winbuild-cmake/build64-v3/install/mingw
> [   0.005][v][cplayer] List of enabled features: av-channel-layout build-date cplayer cuda-hwaccel cuda-interop d3d-hwaccel d3d11 d3d9-hwaccel direct3d dos-paths dvdnav egl-angle egl-angle-win32 egl-helpers ffmpeg ffnvcodec gl gl-dxinterop gl-dxinterop-d3d9 gl-win32 glob glob-win32 gpl iconv javascript jpeg jpegxl lcms2 libarchive libass libavdevice libbluray libm libmpv-shared libplacebo libplacebo-next luajit manpage-build noexecstack openal optimize pdf-build plain-gl rubberband rubberband-3 sdl2 sdl2-audio sdl2-gamepad sdl2-video shaderc spirv-cross stdatomic threads uchardet vapoursynth vector vulkan wasapi win32 win32-desktop win32-executable win32-internal-pthreads zimg zlib
> [   0.005][v][cplayer] Built with NDEBUG.
> [   0.005][d][global] config path: '' -> 'D:\Softwares\mpv\bin'
> [   0.005][d][global] user path: '~~home/' -> 'D:\Softwares\mpv\bin'
> [   0.005][d][global] user path: '~~old_home/' -> ''
> [   0.005][d][global] config path: 'encoding-profiles.conf' -/-> 'D:\Softwares\mpv\bin/encoding-profiles.conf'
> [   0.005][d][global] config path: 'mpv.conf' -> 'D:\Softwares\mpv\bin/mpv.conf'
> [   0.005][d][global] config path: 'config' -/-> 'D:\Softwares\mpv\bin/config'
> [   0.005][v][cplayer] Reading config file D:\Softwares\mpv\bin/mpv.conf
> [   0.005][v][cplayer] Applying profile 'default'...
> [   0.005][v][cplayer] Setting option 'profile' = 'gpu-hq' (flags = 4)
> [   0.005][v][cplayer] Applying profile 'gpu-hq'...
> [   0.005][v][cplayer] Setting option 'scale' = 'spline36' (flags = 4)
> [   0.005][v][cplayer] Setting option 'cscale' = 'spline36' (flags = 4)
> [   0.005][v][cplayer] Setting option 'dscale' = 'mitchell' (flags = 4)
> [   0.005][v][cplayer] Setting option 'dither-depth' = 'auto' (flags = 4)
> [   0.005][v][cplayer] Setting option 'correct-downscaling' = 'yes' (flags = 4)
> [   0.005][v][cplayer] Setting option 'linear-downscaling' = 'yes' (flags = 4)
> [   0.005][v][cplayer] Setting option 'sigmoid-upscaling' = 'yes' (flags = 4)
> [   0.005][v][cplayer] Setting option 'deband' = 'yes' (flags = 4)
> [   0.005][v][cplayer] Setting option 'deband' = 'no' (flags = 4)
> [   0.005][v][cplayer] Setting option 'osc' = 'no' (flags = 4)
> [   0.005][v][cplayer] Setting option 'msg-level' = 'all=no' (flags = 8)
> [   0.005][v][cplayer] Setting option 'ytdl' = 'no' (flags = 8)
> [   0.005][v][cplayer] Setting option 'user-agent' = 'libmpv' (flags = 8)
> [   0.005][v][cplayer] Setting option 'referrer' = '' (flags = 8)
> [   0.005][v][cplayer] Setting option 'hwdec' = 'no' (flags = 8)
> [   0.005][v][cplayer] Setting option 'log-file' = 'C:\Windows\TEMP\mpv_thumbs_cache\Background Removal Like Zoom  OpenCV Python CVZone k7cVPGpnels-41478009\000000.bgra.log' (flags = 8)
> [   0.005][v][cplayer] Setting option 'start' = '4.720617' (flags = 8)
> [   0.005][v][cplayer] Setting option 'frames' = '1' (flags = 8)
> [   0.005][v][cplayer] Setting option 'hr-seek' = 'yes' (flags = 8)
> [   0.005][v][cplayer] Setting option 'audio' = 'no' (flags = 8)
> [   0.005][v][cplayer] Setting option 'vf' = 'scale=200:112' (flags = 8)
> [   0.005][v][cplayer] Setting option 'vf-add' = 'format=bgra' (flags = 8)
> [   0.005][v][cplayer] Setting option 'of' = 'rawvideo' (flags = 8)
> [   0.005][v][cplayer] Setting option 'ovc' = 'rawvideo' (flags = 8)
> [   0.005][f][cplayer] Error parsing commandline option o: option requires parameter
> [   0.005][w][cplayer] Make sure you're using e.g. '--o=value' instead of '--o value'.
> [   0.005][i][cplayer] Exiting... (Fatal error)
> ```

i think the owner is no more taking care? idk for sure 

but there is new project too for thumnail at mpv . :   https://github.com/po5/thumbfast
u may look into that

**Comment by naskya** [comment]
Does #49 solve the issue?

**Comment by OmiChrome** [comment]
> Does #49 solve the issue?

noo , it doesn't 
btw i have switched form that thumbnail worker of THeAMM to new thumnail methoud called [thumfast](https://github.com/po5/thumbfast)

**Comment by OmiChrome** [comment]
just USE [thumfast](https://github.com/po5/thumbfast)
